version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "darabi"
  # Check for Docker image updates
  - package-ecosystem: "docker"
    directory: "/caddy-builder"
    schedule:
      interval: "daily"
    assignees:
      - "darabi"
